### PR TITLE
:bug: fixing bug when updating privileges

### LINKED ISSUE #78: Bug: REMOTE Privilege Causes Infinite State Drift and Syntax Error
## Description

When using the `clickhouse_role` resource with the `REMOTE` global privilege, the provider experiences state drift that leads to an infinite loop and eventually a SQL syntax error.

## Root Causes

This issue has **two related bugs**:

### Bug 1: State Drift - Privilege Expansion Not Handled

ClickHouse internally expands the `REMOTE` privilege into `READ` + `WRITE` privileges. However, the provider doesn't handle this expansion when reading state back from ClickHouse, causing Terraform to detect drift where none exists.

**Flow:**
1. User applies: `privileges = ["REMOTE"]`
2. Provider grants: `GRANT REMOTE ON *.* TO role`
3. ClickHouse stores: `READ + WRITE` (expanded form)
4. Provider reads back: `["READ", "WRITE"]` ❌ (should be `["REMOTE"]`)
5. Terraform detects "drift": Wants to change `["READ", "WRITE"]` → `["REMOTE"]`
6. On re-apply: Revokes `READ + WRITE`, grants `REMOTE` (which expands back to `READ + WRITE`)
7. **Infinite loop!**

### Bug 2: SQL Syntax Error for Global Privileges

When granting global privileges (REMOTE, S3, etc.) with `database = "*"`, the provider generates incorrect SQL that wraps the privilege in `CURRENT GRANTS()`:

**Current (Wrong):**
```sql
GRANT CURRENT GRANTS (REMOTE ON *.*) TO role
```

**Expected (Correct):**
```sql
GRANT REMOTE ON *.* TO role
```

Global privileges should NOT be wrapped in `CURRENT GRANTS()` syntax.

### Step 1: Create Role

```hcl
resource "clickhouse_role" "remote" {
  name       = "remote"
  database   = "*"
  privileges = ["REMOTE"]
}
```

```bash
terraform apply  # ✅ Succeeds
```

**Result in ClickHouse:**
```sql
SELECT role_name, access_type FROM system.grants WHERE role_name='remote';
-- Output:
-- remote  READ
-- remote  WRITE
```

### Step 2: Re-apply (Triggers Drift)

```bash
terraform plan
```

**Output:**
```
# clickhouse_role.remote will be updated in-place
~ resource "clickhouse_role" "remote" {
    ~ privileges = [
        - "READ",
        - "WRITE",
        + "REMOTE",
      ]
  }
```

```bash
terraform apply  # ✅ Completes but revokes all privileges!
```

**Result in ClickHouse:**
```sql
SELECT role_name, access_type FROM system.grants WHERE role_name='remote';
-- Output: (empty - all privileges revoked!)
```

### Step 3: Re-apply Again (Triggers Syntax Error)

```bash
terraform apply
```

**Error:**
```
Error: resource role update: error granting privileges to role remote:
code: 62, message: Syntax error: failed at position 24 (ON): ON *.*) TO remote.
Expected access type
```

## Expected Behavior

1. **First apply**: Role created with REMOTE privilege
2. **Second apply**: No changes detected (state matches reality)
3. **Privileges persist**: REMOTE privilege remains granted

## Actual Behavior

1. **First apply**: Role created, but state shows READ+WRITE instead of REMOTE
2. **Second apply**: Detects drift, revokes READ+WRITE, grants REMOTE (which expands back to READ+WRITE)
3. **Third apply**: All privileges are gone, attempting to re-grant causes syntax error
4. **Infinite loop**: Every apply detects drift

## Impact

- ❌ Cannot use REMOTE privilege reliably
- ❌ Applies same to other expandable privileges (S3, etc.)
- ❌ Causes infinite drift detection
- ❌ Leads to privilege removal on re-apply
- ❌ Causes syntax errors in some scenarios
- ❌ Makes role management unpredictable

## Environment

- **Provider Version**: v3.8.0 (and earlier)
- **Terraform Version**: 1.6.6
- **ClickHouse Version**: 25.12.4
- **Operating System**: macOS (arm64)

## Affected Privileges

This bug affects any privilege that ClickHouse expands internally:

- ✅ `REMOTE` → expands to `READ + WRITE`
- ✅ `S3` → may expand to multiple S3-related privileges
- ⚠️ Other global privileges may have similar issues

### Fix 1: Use SHOW GRANTS Instead of SELECT FROM system.grants

**Root Cause Analysis:**

The provider currently reads privileges using `SELECT FROM system.grants`, which returns the **expanded** form of privileges. When you grant `REMOTE`, ClickHouse internally expands it to `READ + WRITE`, and `system.grants` shows the expanded form.

**Solution:**

Use `SHOW GRANTS` command instead of querying `system.grants`. According to ClickHouse documentation, `SHOW GRANTS` returns the **original granted privileges** (e.g., `REMOTE`) rather than their expanded forms.

### Fix 2: Correct SQL Generation for Global Privileges

In `pkg/resources/role/service.go`, separate global privileges from database-level privileges:

```go
func getGrantQuery(roleName string, privileges []string, database string) string {
    var globalPrivileges []string
    var dbPrivileges []string

    for _, privilege := range privileges {
        if IsGlobalPrivilege(privilege) {
            globalPrivileges = append(globalPrivileges, privilege)
        } else {
            dbPrivileges = append(dbPrivileges, privilege)
        }
    }

    var queries []string

    // Grant global privileges WITHOUT CURRENT GRANTS wrapper
    if len(globalPrivileges) > 0 {
        queries = append(queries, fmt.Sprintf("GRANT %s ON *.* TO %s",
            strings.Join(globalPrivileges, ","), roleName))
    }

    // Grant database-level privileges WITH CURRENT GRANTS when needed
    if len(dbPrivileges) > 0 {
        if database == "system" || database == "*" {
            queries = append(queries, fmt.Sprintf("GRANT CURRENT GRANTS (%s ON %s.*) TO %s",
                strings.Join(dbPrivileges, ","), database, roleName))
        } else {
            queries = append(queries, fmt.Sprintf("GRANT %s ON %s.* TO %s",
                strings.Join(dbPrivileges, ","), database, roleName))
        }
    }

    return strings.Join(queries, "; ")
}
```

## Workaround

Currently, there is no workaround. Users should avoid using `REMOTE` and other expandable global privileges until this is fixed.

## Related Issues

- [ ] S3 privilege may have similar expansion behavior
- [ ] Other global privileges should be audited for expansion

---

**Labels**: `bug`, `priority:high`, `provider:clickhouse`, `area:roles`

### PR DESCRIPTION
**Pull request by IvanOfThings**
- Fixed management for global privileges using SHOW instead of select to verify
- Improved and extended testing for privileges that are expanded by CH after applied
- Added docker-compose with cluster configuration for local testing

### CODE REVIEW

File: pkg/resources/role/service.go [hunk 1]
```diff
@@ -13,36 +13,130 @@ type CHRoleService struct {
...
+	for _, privilegeName := range privilegeNames {
+		grants = append(grants, CHGrant{
+			RoleName:   roleName,
+			AccessType: strings.TrimSpace(privilegeName),
+			Database:   database,
+		})
+	}
+
+	return grants, nil
+}
```
Comment (juan-vg) [inline pkg/resources/role/service.go]: - Makes parsing more robust by handling keyword case insensitively and normalizing whitespace instead of relying on brittle string slicing.
- Explicitly validates the GRANT … ON … TO … structure and returns clearer, more precise errors for malformed statements.
- Verifies that the role specified in the statement matches the expected role, preventing silent misassociation of grants.
- Improves input validation (e.g. empty privileges, invalid scopes) to fail fast on unexpected or unsupported formats.
- Clearly separates supported behavior (global and database-level grants) from unsupported features (table-level grants), making future extensions easier.
- Refactors for readability and maintainability, reducing reliance on positional string assumptions and making the code more self-documenting.

```suggestion
// parseGrantStatement parses a single ClickHouse SHOW GRANTS statement
// and returns the corresponding CHGrant entries.
//
// Supported forms:
//   - GRANT <privileges> ON *.* TO <role>
//   - GRANT <privileges> ON <database>.* TO <role>
//
// Notes:
//   - The role in the statement must match expectedRole
//   - Table-level grants (<database>.<table>) are currently rejected
//   - Privileges are split on commas and normalized via trimming
func parseGrantStatement(statement, expectedRole string) ([]CHGrant, error) {
	stmt := strings.TrimSpace(statement)

	// Normalize keyword case for parsing, but keep original tokens
	upper := strings.ToUpper(stmt)

	if !strings.HasPrefix(upper, "GRANT ") {
		return nil, fmt.Errorf("invalid grant statement (missing GRANT): %q", statement)
	}

	// Split into GRANT <privileges> ON <scope> TO <role>
	grantBody := stmt[len("GRANT "):]
	upperBody := upper[len("GRANT "):]

	onIdx := strings.Index(upperBody, " ON ")
	if onIdx == -1 {
		return nil, fmt.Errorf("invalid grant statement (missing ON): %q", statement)
	}

	privPart := strings.TrimSpace(grantBody[:onIdx])
	rest := grantBody[onIdx+4:]
	upperRest := upperBody[onIdx+4:]

	toIdx := strings.Index(upperRest, " TO ")
	if toIdx == -1 {
		return nil, fmt.Errorf("invalid grant statement (missing TO): %q", statement)
	}

	scopePart := strings.TrimSpace(rest[:toIdx])
	rolePart := strings.TrimSpace(rest[toIdx+4:])

	if rolePart != expectedRole {
		return nil, fmt.Errorf(
			"grant role mismatch: expected %q, got %q",
			expectedRole, rolePart,
		)
	}

	// Parse privileges
	rawPrivileges := strings.Split(privPart, ",")
	privileges := make([]string, 0, len(rawPrivileges))
	for _, p := range rawPrivileges {
		p = strings.TrimSpace(p)
		if p == "" {
			return nil, fmt.Errorf("empty privilege in grant: %q", statement)
		}
		privileges = append(privileges, p)
	}

	// Parse scope
	var database string
	switch {
	case scopePart == "*.*":
		database = "*"

	case strings.HasSuffix(scopePart, ".*"):
		database = strings.TrimSuffix(scopePart, ".*")
		if database == "" {
			return nil, fmt.Errorf("invalid database scope: %q", scopePart)
		}

	default:
		return nil, fmt.Errorf(
			"unsupported grant scope (table-level not supported): %q",
			scopePart,
		)
	}

	grants := make([]CHGrant, 0, len(privileges))
	for _, p := range privileges {
		grants = append(grants, CHGrant{
			RoleName:   expectedRole,
			AccessType: p,
			Database:   database,
		})
	}

	return grants, nil
}

```

**Review by juan-vg — CHANGES_REQUESTED** [review]

File: pkg/resources/role/service.go (hunk 1 above)
Comment (IvanOfThings) [reply pkg/resources/role/service.go]: I like your approach!

**Review by juan-vg — APPROVED** [review]

**Review by juan-vg — APPROVED** [review]
